--- #YAML:1.0
name:               Nmap-Parser
version:            1.21
abstract:           parse nmap scan data with perl
author:
    - Anthony Persaud
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    Storable:   2
    XML::Twig:  3.16
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
